### ISSUE TITLE
How to determine the time complexity of the osqp solver ?

### ISSUE THREAD

**Issue by lith0613** [oxfordcontrol/osqp#114]
I use the tool in my project, and I need to make sure that the time complexity of the solver.
I just use it for solving the common QP problem 
```
min (x^T)Qx+(C^T)x
```
Thanks !

**Comment by goulart-paul** [comment]
Your problem is unconstrained, so the solution will amount to performing the linear solve x = Q\c.

How long it takes to do this will depend on the sparsity of Q.   If you assume that it is completely dense, then the time complexity is roughly that of a Cholesky factorisation and a forward/back solve.

You don't need OSQP to solve this if you really don't have any constraints.
