### ISSUE TITLE
Enforcing strict feasibility 

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [oxfordcontrol/osqp#117]
Hello,

I have a particular problem where the constraints (Ax <= 0) absolutely need to be satisfied. I tried changing `eps_abs` without success. The only way I found was to solve with (A <= -1e-2) to obtain a feasible solution. Is there another way to solve this issue ?

Thank you,

Guillaume Leclerc

**Comment by goulart-paul** [comment]
Do you have the solution polishing option enabled?   If not, I would try that first.

**Comment by GuillaumeLeclerc** [comment]
Yes, I tried both polish and non polish.

**Comment by goulart-paul** [comment]
Does it report whether the solution polishing was successful?   

- If not, then I would suggest tightening the solution accuracy (eps_rel) to 1e-4 or tighter and trying again.

- If so, what is the size the of the constraint violation?

**Comment by GuillaumeLeclerc** [comment]
Thank your for your suggestions.

I tried multiple combinations, without luck:

- `rel_eps= 1e-4` fails at polishing 
- `rel_eps = 5e-5` fails polishing too but the solution is very bad in terms of loss 
- `rel_eps = 1e-5` never finishes no matter the number of iterations I give

**Comment by goulart-paul** [comment]
In that case I think slightly over-tightening your constraints as you have done is the most straightforward solution (i.e. set Ax \le -1e-4 or similar).

Could you provide us with a MWE so we can add it to our list of test problems?

**Comment by GuillaumeLeclerc** [comment]
I tried `Ax \leq 1e-4` but I still had residuals of the same order, I had to push to 1e-2 to get stric enforcement.

Sure ! what kind of format do you expect ?

**Comment by goulart-paul** [comment]
If the problem is smallish and you are working through one of our interfaces, then you could just supply a Matlab/Python/Julia script that reproduces it.   Otherwise some saved problem data from whatever language you are using (e.g. Matlab .mat file, Python pickle file), plus a script showing us what settings you used and the output you get.

You could also run codegen on your problem and supply us with the exported workspace file.

**Comment by gbanjac** [comment]
As described [here](https://osqp.org/docs/solver/index.html#convergence), OSQP does not guarantee constraint satisfaction after a finite number of iterations. Therefore, this is the expected behavior of the solver.

If you want to discuss how to modify the problem in order to enforce feasibility of the original problem, then I think [this forum](https://groups.google.com/forum/#!forum/osqp) is a more appropriate place for such discussion.

Also, you might have a look at a similar discussion in https://github.com/oxfordcontrol/osqp/issues/97.
