### ISSUE TITLE
PROFILING=OFF causes error during make

### ISSUE THREAD

**Issue by pjchaber** [oxfordcontrol/osqp#157]
During compilation, an error occurs:
```
.../osqp/src/util.c:240:6: error: ‘OSQPSettings {aka struct <anonymous>}’ has no member named ‘adaptive_rho_fraction’; did you mean ‘adaptive_rho_interval’?
   new->adaptive_rho_fraction = settings->adaptive_rho_fraction;
```
As far as I have researched it is due to the
```
#  ifdef PROFILING
  c_float adaptive_rho_fraction;  ///< Interval for adapting rho (fraction of
                                  // the setup time)
```
which as soon as I change into
```
#  ifndef PROFILING
```
goes away. I am unfortunately not so familiar with the contents of this code, and therefore I ask for further inspection.

CMake options, that I use to configure project are:
```
cmake -DPRINTING=OFF -DPROFILING=OFF -DCTRLC=OFF -DDFLOAT=ON -DENABLE_MKL_PARDISO=OFF .
```

**Comment by gbanjac** [comment]
It seems that the error occurs due to the wrong `#ifdef` [here](https://github.com/oxfordcontrol/osqp/blob/master/src/util.c#L239-L241). This seems to be fixed in `develop` branch (see [here](https://github.com/oxfordcontrol/osqp/blob/develop/src/util.c#L236-L238)). I managed to successfully compile the code in `develop` branch as long as I do not enable `UNITTESTS` flag.

I will fix the unit tests so that the compilation does not fail when `PROFILING=OFF`.

**Comment by gbanjac** [comment]
The unit tests should now work in `develop` when `PROFILING=OFF`.
