### ISSUE TITLE
crashes when using in another project

### ISSUE THREAD

**Issue by EdsterG** [oxfordcontrol/osqp#17]
When OSQP is compiled with DLONG turned on and I link to it from my project, the project crashes. However when I explicitly add "add_definitions(-DDLONG)" to my cmake file, everything works fine. This is a problem because once the user has compiled OSQP there's no way to tell what options they've compiled with.

**Comment by EdsterG** [comment]
Here's a simple script to reproduce the issue I'm describing:

`
#!/bin/bash

# Clone and build osqp repo
git clone https://github.com/oxfordcontrol/osqp.git && \
    mkdir osqp/build && \
    cd osqp/build && \
    cmake .. && \
    make -j

# Run demo
./out/osqp_demo_direct # This works...


# CD from build folder
cd ../../

# Make osqp_test project
mkdir osqp_test && cd osqp_test

echo "cmake_minimum_required (VERSION 3.2)" >> CMakeLists.txt
echo "project (osqp_debug)" >> CMakeLists.txt
echo "include_directories(../osqp/include)" >> CMakeLists.txt
echo "link_directories(../osqp/build/out)" >> CMakeLists.txt
echo "add_executable(osqp_demo_direct examples/osqp_demo_direct.c)" >> CMakeLists.txt
echo "target_link_libraries(osqp_demo_direct osqpdirstatic)" >> CMakeLists.txt

# Copy examples from osqp repo
cp -r ../osqp/examples examples

# Build osqp_test
mkdir build && \
    cd build && \
    cmake .. && \
    make -j

./osqp_demo_direct # This crashes... why?
`

**Comment by bstellato** [comment]
Thank you for reporting this!  I think your script works if `echo "add_definitions(-DDLONG)" >> CMakeLists.txt` is added. 

Long integers are enabled by default with the compiler flag `DLONG`. However, when you add OSQP to a new project without specifying `DLONG`, these lines
https://github.com/oxfordcontrol/osqp/blob/92613ef43994e47dcaab0d43aed7e0360e3f5328/include/glob_opts.h#L69-L73
define `c_int` as a standard (not long) integer because `DLONG` is not defined. I will fix it in the next days. It can be easily done by just defining another option that negates `DLONG`, e.g., something like `DSHORT`.

**Comment by EdsterG** [comment]
Thank you, yes my script does work when I add "add_definitions(-DDLONG)". However, when OSQP is compiled with DLONG OFF, adding "add_definitions(-DDLONG)" will break it again.

**Comment by bstellato** [comment]
It should be now fixed in the `develop` branch 037575f6815978f3f045010130bf71bdb36fdcbe. `cmake` now generates the file `glob_opts.h` from `glob_opts.h.in` by populating the values of the compiler directives used during the library compilation. In this way, the user is able to see which options were used to generate the library. There is no need to pass the `DLONG` option in the second project.

The following script should work without crashing
```bash
#!/bin/bash

# Clone and build osqp repo
git clone -b config_file_cmake https://github.com/oxfordcontrol/osqp.git && \
    mkdir osqp/build && \
    cd osqp/build && \
    cmake .. && \
    make -j

# Run demo
./out/osqp_demo # This works...


# CD from build folder
cd ../../

# Make osqp_test project
mkdir osqp_test && cd osqp_test

echo "cmake_minimum_required (VERSION 3.2)" >> CMakeLists.txt
echo "project (osqp_debug)" >> CMakeLists.txt
echo "include_directories(../osqp/include)" >> CMakeLists.txt
echo "link_directories(../osqp/build/out)" >> CMakeLists.txt
echo "add_executable(osqp_demo examples/osqp_demo.c)" >> CMakeLists.txt
echo "target_link_libraries(osqp_demo osqpstatic)" >> CMakeLists.txt

# Copy examples from osqp repo
cp -r ../osqp/examples examples

# Build osqp_test
mkdir build && \
    cd build && \
    cmake .. && \
    make -j

./osqp_demo
```

Note that the `dir` and `direct` part of the names have been removed. In the next release we will not make any distinction between the `direct` and the `indirect` linear solvers. There will be just a single library `libosqp` having access to several `direct`/`indirect` solvers.

**Comment by bstellato** [comment]
I would close this issue if the problem no longer appears.

**Comment by EdsterG** [comment]
The problem has been resolved, thank you! =)
