### ISSUE TITLE
No Windows or macOS Python 3.5 wheels on Pypi

### ISSUE THREAD

**Issue by mtreinish** [oxfordcontrol/osqp#187]
With the recent release of osqp 0.6.0 on pypi there are no prebuilt binary wheels uploaded for macOS or Windows python3.5 hosted on pypi. There are only manylinux1 and manylinux2010 wheels for python3.5: https://pypi.org/project/osqp/#files. Unlike in the previous release 0.5.0 which had wheels for all 3 platforms on python 3.5: https://pypi.org/project/osqp/0.5.0/#files . 

This caught us by surprise and [broke](https://dev.azure.com/qiskit-ci/qiskit-ignis/_build/results?buildId=2333&view=logs&j=76ed1102-9071-5354-720f-6f09bbc9f0c0&t=be5b5b08-9bc6-5c95-c335-5e65f8440ac3&l=235) our Windows CI system which does not have the prerequisites installed for building osqp from source.  Was this just an oversight or is the plan to drop support for python 3.5 on these platforms?

**Comment by bstellato** [comment]
Can you please try again? They should be there now.

**Comment by mtreinish** [comment]
Thanks for uploading them. Confirmed it fixed our windows ci in Qiskit/qiskit-ignis#270. We can close this now.

As a related aside one thing I've found useful in other projects with python bindings for a C library is to leverage [cibuildwheel](https://github.com/joerick/cibuildwheel/) to automatically build wheels and upload them to pypi whenever a tag is pushed. If that's something you think would be useful here I can write a PR to do that.

**Comment by bstellato** [comment]
Thank you for the suggestion. I tried it in the past but I never managed to make it run with our cmake-based script. However, I am using [multibuild](https://github.com/matthew-brett/multibuild) in the [osqp-wheels](https://github.com/oxfordcontrol/osqp-wheels) repository for building wheels.

If you think you can manage to make a working PR for that with automatic tag-release, it would be appreciated. At the moment the most updated branch for our code is `develop`. Otherwise we will continue using multibuild which works well. We anyway need a separate repository for the conda package in [osqp-feedstock](https://github.com/conda-forge/osqp-feedstock).
