### ISSUE TITLE
questions on using osqp_update_A with sparsity pattern modified

### ISSUE THREAD

**Issue by lianglia-apollo** [oxfordcontrol/osqp#219]
Is there a method to update_A matrix with its sparsity pattern modified?
It seems that the current method requires that the new A has the same size as the previous A.

**Comment by bstellato** [comment]
Unfortunately you need to create a new workspace to do that. This is because you need to rerun the setup and perform the memory allocations for the new sparsity pattern.

If you already know the sparsity pattern of the second `A`, you can preallocate all its elements when you define the first matrix `A` and set some of them to `0`. In this way you would be able to update their values without changing the sparsity pattern.
