### ISSUE TITLE
Graceful Exit OSQP

### ISSUE THREAD

**Issue by Ajin2305** [oxfordcontrol/osqp#226]
Hi,

I am trying to use  the solver on a real time system (**Using C**). There are times when data produced in real time could consist an error or some of the data might be delayed( Sending 0s on Dynamic limits causing it to be non-convex). When such data is given as input to the solver I end up with two errors

1. Error in LDL_factor : Error in KKT matrix LDL factorization when computing nonzero elements. Problem seems to be non-convex.
2.Error in osqp_setup :KKT matrix factorization, Problem seems to be non-convex.

I think its one error that has produced these messages
(Process Returns 139 SEG FAULT since variables are not destroyed)
After which solver force exits the program. This isn't favourable to me as i would like to  solver to free its used memory and have the solver send a status about that would allow me to continue running the solver for the next set of data that comes.

I hope i have made it clear enough for you. Providing a sample script seems difficult to me.
Kindly advice

**Comment by goulart-paul** [comment]
I don't quite understand the problem, since putting 0s on the 'dynamic limits' (presumably you mean 'l' and 'u' here) should not cause this error.    The error you are seeing is most likely to be have been caused by specifying an indefinite or negative semi-definite 'P' matrix.   

That said, it still should not segfault on you.   Can you please provide a minimum working example of the problem?   It doesn't need to be from your application, just an example QP with 2-3 variables that produces the same fault.

**Comment by Ajin2305** [comment]
Hi,

You are correct about the P matrix being indefinite. I just gave 0s on limits as an example but any sensor could return a 0 causing my P matrix to be indefinite. All i want is for the solver not to force exit. I want it to return a flag/ message that will help me understand an error like this has come. 



About the Segfault. It isn't an issue. The segfault is occurring since the program is force exited without clearing memory. I have used the osqp_demo file in the example to indicate the issue. I have add comments there as well. 

[osqp_demo.zip](https://github.com/oxfordcontrol/osqp/files/3917579/osqp_demo.zip)

**Comment by gbanjac** [comment]
In the example you provided, the value returned by the `osqp_setup` function (stored in `exitflag`) is `5`. According to the [documentation](https://osqp.org/docs/interfaces/status_values.html#solver-errors), this means that your problem is non-convex, that is, the `P` matrix is not positive semidefinite.

You should check the value of `exitflag` before calling the `osqp_solve` function.

**Comment by goulart-paul** [comment]
I think has been answered.   Feel free to reopen if not.
