### ISSUE TITLE
The implementation is not stateless.

### ISSUE THREAD

**Issue by markcsie** [oxfordcontrol/osqp#235]
If calling `osqp_solve(work)` consecutively, it changes some internal states of `work`. This is quite counter-intuitive mathematically.

One state has been found so far:
1. Osqp updates `work->settings->rho` after finishing if `adaptive_rho` is true, which I think it shouldn't because it's just an input parameter.

**Comment by gbanjac** [comment]
As documented [here](https://osqp.org/docs/solver/index.html#rho-step-size), OSQP updates the `rho` parameter if `adaptive_rho` is true. If such behavior is undesirable, then the user can set `adaptive_rho` to false.

OSQP also changes the initial iterates to the previously computed solution. This can be suppressed by setting `warm_start` to false.

Why exactly is the non-stateless implementation problematic?

**Comment by markcsie** [comment]
`work = ...
work->settings->rho = 1.0
a = osqp_solve(work)
b = osqp_solve(work)
c = osqp_solve(work)
// a != b != c`
To make a==b==c, we have to do 
`work = ...
work->settings->rho = 1.0
a = osqp_solve(work)
work->settings->rho = 1.0
b = osqp_solve(work)
work->settings->rho = 1.0
c = osqp_solve(work)
// a == b == c`
This is a little bit counter-intuitive for users especially in this case where `rho` is called a `setting`. `adaptive_rho` can still be true for each call, it just needs to be recovered at the end of each call. 
But for a user of `osqp` it's not trivial to know what has been changed at each call unless we dig into the implementation. If some other parameters are added into `osqp` in the future, the user code needs to be modified in order to keep a==b==c.

**Comment by gbanjac** [comment]
I think that even in the second example you will not necessarily have `a==b==c` due to the aforementioned warm starting, i.e., the initial iterates would change after each call to `osqp_solve`.

Why don't you instead make three instances of the solver by having three `OSQPWorkspace` pointers and perform the desired operations on different "objects"?

**Comment by markcsie** [comment]
I know instantiating different instances would solve the problem. I just wanted to propose an idea that could avoid potential bugs for users. Actually I am a user of `casadi`, in this case, I'll have to instantiate different instances of `casadi`, which doesn't seem to be a natural thing to do.

As for `warm_start`, I think another implementation to avoid confusion is to force user to provide `warm_start_values` every time `warm_start` is set to true, instead of reusing values from the last call to `osqp_solve`.

**Comment by bstellato** [comment]
I understand it could cause confusion. However, it is very important for algorithmic purposes to have the adapt rho and have the best value available. If we keep rho setting without modifying it, it can happen that when the user requests its value from any interface it gets just the old rho. (which is useless). In addition, reusing the best rho value in subsequent solves is crucial in online optimization.

I would be happy to add a section in the osqp settings documentation where we describe the rho behavior in detail.

Regarding warm-starts. Commercial solvers such as Gurobi also implicitly reuse the previous solution: https://www.gurobi.com/documentation/9.0/examples/lpmod_c_c.html
As you can see in the example, in order to clear the initial primal/dual solution you have to explicitly reset the solver. I think that's the intended behavior.

If you have an issue with OSQP and CasADi I suggest you to open an issue in the CasADi github repo mentioning this issue with a minimal working example so that both the CasADi developers and us can look into it.
