### ISSUE TITLE
objective gets worse after interations

### ISSUE THREAD

**Issue by colinfang** [oxfordcontrol/osqp#241]
I have got a tiny problem, osqp fails to converge to a good solution with or without `adaptive_rho`

Is it normal that the objective gets worse at iter 50?

```
problem:  variables n = 4, constraints m = 7
          nnz(P) + nnz(A) = 26
settings: linear system solver = qdldl,
          eps_abs = 1.0e-04, eps_rel = 1.0e-03,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 ,
          sigma = 1.00e-06, alpha = 1.60, max_iter = 4000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1  -5.9516e-02   4.28e+00   1.66e-02   1.00e-01   2.30e-05s
  50   7.5841e-12   5.96e-10   1.15e-13   1.00e-01   4.09e-05s

status:               solved
solution polish:      unsuccessful
number of iterations: 50
optimal objective:    0.0000
run time:             5.51e-05s
optimal rho estimate: 9.11e+03
```

**Comment by gbanjac** [comment]
It is not clear what you mean by "a good solution". We measure the quality of a solution in terms of the values of its primal and dual residuals. In your example you get residuals in the order of `1e-10` and `1e-13` so this should definitely be considered as a solution of high accuracy.

OSQP is based on a method that does not necessarily decrease the objective value as the iterations progress because the iterates at which the objective value is computed are not necessarily feasible.

**Comment by goulart-paul** [comment]
The solution did not get worse at iteration 50, and the solver did not fail to converge.     The right way to assess to progress of the solver is from the primal and dual residual terms, both of which went to zero.   

Note that the 'unsuccessful' part of the output does not mean that the solver failed, but only that the final 'polish' attempt did not improve things.     The important thing is that `status` returned as `solved`.

It seems that your problem is reasonably small, so if you post it as an example we can use it as one of our internal development examples if we try to improve the polishing step.

**Comment by colinfang** [comment]
Thanks for the explanation. I will try finding a minimal example and reopen the comment
