### ISSUE TITLE
Variable fixing in problem?

### ISSUE THREAD

**Issue by colinfang** [oxfordcontrol/osqp#244]
If I know the exact value of a variable, is the only way to fix it is to set both lb & ub to that value?

However in OSQP I found the more fixed variables I have, the slower the solve becomes as the problem becomes bigger. Also the value of those fixed variables tend to fluctuate slightly through iterrations. 

Therefor I often have to manually transform the problem to get rid of those fixed variables, which is less ideal.

I used Gurobi before and fixed variables are pruned (constant propagation & domain progpagation) in the presolve stage so that they have no impact in the actual solve.

I wonder if it is a sensible thing to try in OSQP as well?

**Comment by goulart-paul** [comment]
Yes, the only way to impose an equality constraint is to set the corresponding upper and lower bounds equal to each other.   As you observed, these implicit equality constraints are not guaranteed to be satisfied exactly at every iteration.

We do not prune variables or otherwise preprocess the problem along those lines.
