### ISSUE TITLE
Is there any strategies or advice to reduce the number of iterations?

### ISSUE THREAD

**Issue by luoyin500** [oxfordcontrol/osqp#253]

**Comment by BaymaxArnO** [comment]
I did some experiments and found that lowering the convergence conditions `eps_abs, eps_rel, eps_prim_inf, eps_dual_inf` can reduce the number of iterations. For example, set `eps_abs, eps_rel` are `1e-2`, meanwhile set `eps_prim_inf, eps_dual_inf` are `1e-3`. 
However, please ensure that the accuracy of the results meet your requirements if you take this strategy.

**Comment by luoyin500** [comment]
Of course,  just loosing the convergence conditions like eps_abs, eps_rel, eps_prim_inf, eps_dual_inf and so on is not unacceptable in term of the result.

**Comment by bstellato** [comment]
Unfortunately, there is no magic rule to reduce them in all cases. In general, rescaling the problem data greatly helps (change of variables or rescale the cost). Another idea if the problem is an LP, is to add a small quadratic regularization to make it strictly convex.

If you have a specific problem, please post it to the [OSQP Forum](https://osqp.discourse.group/) and we can have a look at how to improve the convergence. It is the more appropriate place for this kind of questions.
