### ISSUE TITLE
Something different between OSQP thesis and code implementation

### ISSUE THREAD

**Issue by BaymaxArnO** [oxfordcontrol/osqp#254]
Hi, recently I read the source code to deepen my understanding of OSQP.  Today, I found that the source code implementation is different from the OSQP thesis.
In the **Algorithm 1** of OSQP thesis,  (sry about that I don't know how to put math formula on it)
 

> z_tilde_k+1 = z_k + rho_inv * (v_k+1 - y_k)    

but in the source code, (`solve_linsys_qdldl` function in `qdldl_interface.c`)

> b[j + s->n] += s->rho_inv_vec[j] * s->sol[j + s->n];

It seems to be that **the `y_k` item has been ignored** in the code implementation.
I want to know if I have misunderstood the code, or it is really a mistake in the implementation.
Waiting for your reply~

**Comment by gbanjac** [comment]
I assume you mean the [OSQP paper](https://arxiv.org/pdf/1711.08013v3.pdf) when referring to the "OSQP thesis". I don't think the code is wrong. Note that the lower `m` elements of vector `b` are set to `z^k - rho_inv*y^k`. Since we store the solution of the linear system in the same vector, we then need to add only `rho_inv*nu` to the lower `m` elements of `b`.

**Comment by BaymaxArnO** [comment]
> I assume you mean the [OSQP paper](https://arxiv.org/pdf/1711.08013v3.pdf) when referring to the "OSQP thesis". I don't think the code is wrong. Note that the lower `m` elements of vector `b` are set to `z^k - rho_inv*y^k`. Since we store the solution of the linear system in the same vector, we then need to add only `rho_inv*nu` to the lower `m` elements of `b`.

It is my misunderstanding of the source code. Thank you for making it clear!
