### ISSUE TITLE
Workspace Allocation Error!!

### ISSUE THREAD

**Issue by prateekkrjain** [oxfordcontrol/osqp#290]
Hi,

I am getting the following errors while executing the QP solver with In-equality constraints.
```ERROR in LDL_factor: Error in KKT matrix LDL factorization when computing the nonzero elements. The problem seems to be non-convex
ERROR in osqp_setup: KKT matrix factorization.
The problem seems to be non-convex.
ERROR :  Workspace allocation error!```

Can you please let me know what could be going wrong??

Thanks,

**Comment by goulart-paul** [comment]
The problem is that your `P` matrix has a negative eigenvalue.   That could be either because 1) it really has a negative eigenvalue, or 2) you have not passed it to the solver correctly.   In the latter case, users sometimes get this error if they don't realise that OSQP only uses entries from the upper triangular part of the `P` that you provide, and then assumes that it is symmetric.

**Comment by prateekkrjain** [comment]
@goulart-paul - Thank you for a quick response. I will check my data for both cases, but just to be clear - in the second point in the P matrix P[A][B] should be equal to P[B][A] right?

**Comment by goulart-paul** [comment]
If you are using OSQP through the C interface, then you only need to provide the entries from the upper triangular part of P.   OSQP will then just assume that `P_{i,j} = P_{j,i}`.

**Comment by prateekkrjain** [comment]
I am using Python, but I understand it now. I am currently passing the full matrix, but I need to pass only the Upper triangle.
Thank you so much for the help.

**Comment by goulart-paul** [comment]
If you are using Python then you do not need to pass only the upper triangular part, but OSQP will ignore the lower triangular part.   it is explained in the documentation here: https://osqp.org/docs/interfaces/python.html

**Comment by prateekkrjain** [comment]
Ok, I will go through the doc.

**Comment by prateekkrjain** [comment]
@goulart-paul I made sure all the elements in the P matrix are non-negative, but still, I am getting the same error. 

Actually, I have a maximization problem and I have converted it to minimization by keeping P as -P and q as -q. Do you think it is because of that? Is there any better way to handle it?

**Comment by goulart-paul** [comment]
The requirement on the matrix `P` is that it must be positive semidefinite, not that it must have non-negative entries.   If it is not positive semidefinite then your problem will be non-convex and a lot harder to solver.   OSQP is not the appropriate solver for that case.

**Comment by prateekkrjain** [comment]
Yes, I checked the Eigenvalues of P have some negative values, so, this cannot be used directly. Thanks for all the help.

**Comment by chiwanii** [comment]
Hi I also have a question about osqp

1. I'd like to solve a qp with 10*10 matrix and want to make a random matrix. and it seems that I shouldn't use a random matrix because it can have a negative eigenvalue. right? 
2. and I used this code
import osqp
import numpy as np
from scipy import sparse


# Define problem data
P = sparse.csc_matrix(np.random.uniform(1, 10, size=(10, 10)))
q = np.random.uniform(0, 9, size=10)
Gs= np.random.uniform(0, 9, size=10)
print("der Maßstab für Gs:", Gs)
A = sparse.csc_matrix(np.diag(-1*Gs))

u = np.zeros(10) ## Rechte Seite von der Ungleichung




# Create an OSQP object
prob = osqp.OSQP()

# Setup workspace and change alpha parameter
prob.setup(P, q, A, u, alpha=1.0)

# Solve problem
res = prob.solve()

but the result is > ValueError: Workspace allocation error!

when I use this same variablen with solver cvxopt, it worked very well. what would be a problem that I made?

thank you!!!

**Comment by gbanjac** [comment]
Matrix `P` should be symmetric and positive semidefinite. The matrix you create is neither symmetric nor PSD.

**Comment by Vldchlms** [comment]
Actually, I have the same issue when the matrix is large.

Here is the code:

n1 = 5000
n2 = 5000

lm1 = 5
lm2 = 5

dim1 = n1
dim2 = n2

sigma = 10

for i in range(n1):
    for j in range(n2):
        theta[i, j] = 2*i + 5*j

data = theta + sigma * np.random.randn(dim1 * dim2).reshape([dim1, dim2])

d = np.ones(dim1*dim2)
D1 = sparse.diags([d,-d],[0,1],format='csr')
D1 = D1[np.arange(1,dim1*dim2+1)%dim1 !=0,]

d = np.ones((dim1*dim2 - dim1))
D2 = sparse.diags([d,-d],[0,dim1], shape = (dim1*dim2 - dim1, dim1*dim2), format='csr')

D = sparse.vstack((D1, D2))

P = D@D.transpose()     
d = np.ones(np.shape(D)[0]+1)
A = sparse.diags([d],[0], format='csr')

y = np.asmatrix(data).transpose().getA1()
# Create an OSQP object
y = y.reshape(-1,1)
q = -y.transpose()@D.transpose()
q = q.reshape(-1,1)

#l = np.zeros(np.shape(D)[0]+1)
l = -lm1*np.ones(np.shape(D)[0]+1)
u = (lm1 + lm2)*np.ones(np.shape(D)[0]+1)
prob = osqp.OSQP()
# Setup workspace and change alpha parameter
prob.setup(P, q, A, l, u, alpha=1.0)
# Solve problem
res = prob.solve()
dl_sol = res.x
y_sol = y -  D.transpose()@dl_sol.reshape(-1,1)



When n1 = 5000 n2 = 5000 the code works.
