### ISSUE TITLE
Matlab Compilation error

### ISSUE THREAD

**Issue by alecjacobson** [oxfordcontrol/osqp#56]
I'm following the instructions:

```
!git clone --recurse-submodules https://github.com/oxfordcontrol/osqp-matlab
cd osqp-matlab
make_osqp
```

But I get the following output error:

```

Error using mex
'/Users/ajx/Dropbox/l1/osqp-matlab/osqp_mex.mexmaci64' is compiled
with incompatible options '-R2017b' and -R2018a'. For more
information, see MEX file compiled with incompatible options.
Error in make_osqp (line 178)
    eval(cmd); 
```

I'm on Mac OS X 10.12 with MATLAB R2018a

**Comment by alecjacobson** [comment]
(I also tried the precompiled binaries but those immediately crashed my matlab).

**Comment by goulart-paul** [comment]
I have modified make_osqp.m to fix this issue (I think).   Could you try updating from the most recent commit and trying again?

Note that I don't actually have 2018a installed, so I can't be sure if the fix will work or not.

**Comment by goulart-paul** [comment]
I have modified make_osqp.m to fix this issue (I think). Could you try updating from the most recent commit and trying again?

Note that I don't actually have 2018a installed, so I can't be sure if the fix will work or not.

**Comment by alecjacobson** [comment]
Thanks! That did it.

**Comment by alecjacobson** [comment]
Oops. Sorry, no it didn't work (mistook a different problem for success). I'm still getting the same error.

**Comment by goulart-paul** [comment]
We have made a fix to both make_osqp.m and the main osqp CMake configuration files.   We have run and tested it on R2016a and R2018a on OSX and also on Windows R2018a.

Could you try again with the most recent commit?   Note that the osqp submodule has also been updated.

**Comment by goulart-paul** [comment]
It appears that the fix we made has broken printing.   The solve probably works without issue, but the 'verbose' option is effectively ignored.   Will try to fix that ....

**Comment by goulart-paul** [comment]
Fix is here: https://github.com/oxfordcontrol/osqp-matlab/commit/0f7f296386ff37d25ec9b84cddd5d76bc70445bf

Could you try it and let us know if it works for you?

**Comment by alecjacobson** [comment]
I immediately get an error:

```
Error using munlock
The file 'osqp_mex' is not locked.
Error in make_osqp (line 48)
munlock osqp_mex; 
```

If I comment out this line then I get the following linker errors:

```
Undefined symbols for architecture x86_64:
  "_SetInterruptEnabled", referenced from:
      _startInterruptListener in
      libosqpstatic.a(ctrlc.c.o)
      _endInterruptListener in
      libosqpstatic.a(ctrlc.c.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1
(use -v to see invocation)
```

**Comment by goulart-paul** [comment]
The first problem is corrected here:
https://github.com/oxfordcontrol/osqp-matlab/commit/bbe2e4f90284084e9eaea1734342a568b0d8fe72

Basically the problem was that 'munlock' fails if the file being unlocked does not exist.   Commenting out as you did works; I have wrapped it in an 'mislocked' conditional, which also works.

For the linker problem : I believe that this issue is already fixed.   Possibly what has happened is that you switched branches to the R2018a-compatibility branch in osqp-matlab, but did not update the submodule in osqp_sources after doing so.

The following works for me on a very similar platform to yours.   From the terminal:

`git clone --recursive https://github.com/oxfordcontrol/osqp-matlab.git`
`cd osqp-matlab`
`git checkout 2018a-compatibility`
`git submodule update`

Then in Matlab:

`make_osqp`

**Comment by alecjacobson** [comment]
Compilation works now.

And examples seem to work.

> FWIW, if I try fresh using the [instruction here for Binaries](http://osqp.readthedocs.io/en/latest/installation/matlab.html). I just get `Solver interrupted` and no solution.
