### ISSUE TITLE
Dense matrix interface

### ISSUE THREAD

**Issue by ahoarau** [oxfordcontrol/osqp#71]
I'm using qpOASES in a control loop and i'd like to interface osqp using my existing dense matrices.
My main constraint is no memory allocations in the control loop.
What I have so far : 

```cpp
auto Ps = eigP.sparseView();
auto As = eigA.sparseView();
osqp_data.P = csc_matrix(n, n Ps.nonZeros(), Ps.valuePtr(), Ps.innerIndexPtr(), Ps.outerIndexPtr());
osqp_data.q = eigq.data();
osqp_data.A = csc_matrix(m,n, As.nonZeros(), As.valuePtr(), As.innerIndexPtr(), As.outerIndexPtr());
osqp_data.l = eigl.data();
osqp_data.u = eigu.data();
// Setup the problem = memory allocations
work = osqp_setup(&osqp_data, &settings);
//
// Enter the realtime control loop
//
// Solve the problem
osqp_solve(work); // --> success
// update P and A and solve again
osqp_update_P_A(work, Ps.valuePtr()
                   , Ps.innerIndexPtr() // or 0 to copy everything ?
                   , Ps.nonZeros() // or n x n ?
                   , As.valuePtr()
                   , As.innerIndexPtr() // or 0  to copy everything ? 
                   , As.nonZeros()); // or m x n ?
                   ) //--> 0
osqp_solve(work); // --> fail
```

I can't get the solver to find anything good after `osqp_update_P_A` and I get #70 .

Annexe questions : 
1. Using sparse matrices, I'm guessing that in the worse case scenario I'll have `n x n` non-zeros values for P and `m x n` values for M ? Does it change anything in terms of memory allocations for the `osqp_setup` ?
2. Are you working on a raw-buffer/dense matrix interface ?

**Comment by bstellato** [comment]
Unfortunately we are not planning to work on a dense matrix interface since the solver is designed for sparse problems. 

However, I think you are very close to getting something working. The documentation of the function is [here](http://osqp.readthedocs.io/en/latest/interfaces/CC++.html#_CPPv315osqp_update_P_AP13OSQPWorkspaceP7c_floatP5c_int5c_intP7c_floatP5c_int5c_int). If you are changing the whole matrices (and not only part of them) you just need to call


```c
osqp_update_P_A(work, Ps.valuePtr(), OSQP_NULL, 0, As.valuePtr(), OSQP_NULL, 0)
```

However, make sure that your matrix `Ps` is stored in upper-triangular format. This means that the vector `Ps.valuePtr()` needs to contain only the values in the upper-triangular part of the matrix. I suspect you have to use the [TriangularView](https://eigen.tuxfamily.org/dox/classEigen_1_1TriangularView.html) method in Eigen.

**Comment by ahoarau** [comment]
Thanks for your fast answer. Indeed it's getting close, but now i'm getting : 
```
ERROR in osqp_update_P: new KKT matrix is not quasidefinite
Could not update P

1 0 0 0 0.632811 0.328278 0.328278 -0.174145 0.328278 -0.0419757 0.0656347 0.0421435 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 1 0 -0.632811 0 -0.210785 -0.210785 -0.271215 -0.210785 -0.0653733 -0.0421436 0.0656347 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 1 -0.328278 0.210785 0 0 -0.390124 0 0.390124 0 -0.000124227 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 1.50822 -0.0691961 0.133387 0.133387 1.14117 0.133387 -0.928171 -0.513633 0.799977 -0.000860514 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 1.44488 0.207738 0.207738 -0.732736 0.207738 0.595972 -0.799936 -0.51366 -0.00134017 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 1.1522 1.1522 6.93889e-18 1.1522 -1.38778e-17 0.031226 1.73472e-18 -0.999999 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 1.15221 6.93889e-18 1.1522 -1.38778e-17 0.031226 1.73472e-18 -0.999999 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 1.25609 6.93889e-18 -1.12716 -5.55112e-17 0.974908 -1.0842e-19 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 1.15221 -1.38778e-17 0.031226 1.73472e-18 -0.999999 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 1.15824 5.55112e-17 -1.00611 1.0842e-19 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 1.00609 -5.55112e-17 0.000796327 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 1.00609 -1.0842e-19 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 1.00001 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 1e-08 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 1e-08 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1e-08 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1e-08 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1e-08 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1e-08 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1e-08 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1e-08 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1e-08 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1e-08 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1e-08 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1e-08 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1e-08 

ERROR in osqp_update_A: new KKT matrix is not quasidefinite
Could not update A

-213.626 0 0 0 -2.78927 -1.02812 -1.02813 1.66621 -1.01641 0.000736826 -0.00196648 -0.00126946 -3.98125e-18 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 -213.626 0 2.78927 0 0.692414 0.691642 2.59497 0.709901 0.00114754 0.00128775 -0.00197707 -1.17838e-17 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 -213.626 1.02812 -0.692414 0 0 1.23883 0 -1.23883 0.0265079 3.70251e-06 1.92183e-20 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 2.78927 1.02812 -4.85835 0.179036 -0.467695 -0.46762 -2.15975 -0.510827 0.39168 0.0370049 -0.0593565 6.03011e-05 0 0 0 0 0 0 0 0 0 0 0 0 0 
-2.78927 0 -0.692414 0.179036 -4.7223 -0.745103 -0.745103 1.40082 -0.717362 -0.265548 0.0650434 0.0381125 9.39134e-05 0 0 0 0 0 0 0 0 0 0 0 0 0 
-1.02812 0.692414 0 -0.467695 -0.745103 -0.696637 -0.565936 -0.0194523 -0.513891 -3.59419e-05 -0.000953194 4.52837e-05 0.0700756 0 0 0 0 0 0 0 0 0 0 0 0 0 
-1.02813 0.691642 0 -0.46762 -0.745103 -0.565936 -0.565936 -0.0194523 -0.513891 -3.59419e-05 -0.000953194 4.52837e-05 0.0700756 0 0 0 0 0 0 1 0 0 0 0 0 0 
1.66621 2.59497 1.23883 -2.15975 1.40082 -0.0194523 -0.0194523 -1.6167 -0.027289 0.473487 -0.00399804 -0.0712686 4.07259e-18 0 0 0 0 0 0 0 1 0 0 0 0 0 
-1.01641 0.709901 0 -0.510827 -0.717362 -0.513891 -0.513891 -0.027289 -0.513891 -3.59419e-05 -0.000953194 4.52837e-05 0.0700756 0 0 0 0 0 0 0 0 1 0 0 0 0 
0.000736826 0.00114754 -1.23883 0.39168 -0.265548 -3.59419e-05 -3.59419e-05 0.473487 -3.59419e-05 -0.474033 0.0039896 0.0722084 7.54127e-19 0 0 0 0 0 0 0 0 0 1 0 0 0 
-0.00196648 0.00128775 0.0265079 0.0370049 0.0650434 -0.000953194 -0.000953194 -0.00399804 -0.000953194 0.0039896 -0.0763968 -4.02157e-08 -5.58031e-05 0 0 0 0 0 0 0 0 0 0 1 0 0 
-0.00126946 -0.00197707 3.70251e-06 -0.0593565 0.0381125 4.52837e-05 4.52837e-05 -0.0712686 4.52837e-05 0.0722084 -4.02157e-08 -0.0722077 -7.50379e-19 0 0 0 0 0 0 0 0 0 0 0 1 0 
-3.98125e-18 -1.17838e-17 1.92183e-20 6.03011e-05 9.39134e-05 0.0700756 0.0700756 4.07259e-18 0.0700756 7.54127e-19 -5.58031e-05 -7.50379e-19 -0.0700757 0 0 0 0 0 0 0 0 0 0 0 0 1 
```

I'm guessing that it has something to do with the very low diagonal value `1e-8`.

**Comment by bstellato** [comment]
I computed the eigenvalue of the `P` matrix from the upper triangular portion that you sent and it looks positive semidefinite. I think the problem might be in the vector that you pass. Are you sure your Eigen sparse matrices are in Compressed Sparse Column format?  Did you run `makeCompressed` from [here](https://eigen.tuxfamily.org/dox/group__TutorialSparse.html)?

It is quite hard for me to debug the code without a minimal working example. Would it be possible for you to create one? 

I know of the project [osqp-eigen](https://github.com/GiulioRomualdi/osqp-eigen) where @GiulioRomualdi wrote an Eigen interface for OSQP. Unfortunately it is not official yet and I am not sure how much time he would have to support it, but you could have a look at it.

Regarding memory allocations for full matrices, the sparse format is less efficient than the dense matrix format because you need to allocate the data as well as the indices vectors. However, most of the problems are sparse. For example, if you are solving a model predictive control (MPC) problem with OSQP, I strongly suggest you to formulate it in sparse form by keeping both states `x` and inputs `u` as variables. You can find an example in various languages [here](http://osqp.readthedocs.io/en/latest/examples/mpc.html).

**Comment by ahoarau** [comment]
in `osqp-eigen` they seem to use triplets, but I'm afraid of the the `push_backs` in the control loop.
To summarize I'm doing this : 
```c++
Eigen::MatrixXd eigPupper = eigP.triangularView<Eigen::Upper>();
Eigen::SparseMatrix<double, Eigen::ColMajor> Ps = eigPupper.sparseView();
Eigen::SparseMatrix<double, Eigen::ColMajor> As = eigA.sparseView();
Ps.makeCompressed();
As.makeCompressed();
```

**Comment by bstellato** [comment]
It is really hard for me to understand what is wrong without a minimal working example. Would it be possible for you to provide one?

**Comment by bstellato** [comment]
I am closing this issue because it has been inactive for too long. If you still have problems feel free to reopen it or to create a new issue.
