### ISSUE TITLE
understanding c interface

### ISSUE THREAD

**Issue by esquires** [oxfordcontrol/osqp#77]
I am having some difficulty understanding the demo for c-code located here: https://osqp.org/docs/examples/demo.html#c

In particular, I am wondering what the following lines mean:

```[c]

    c_int P_i[4] = {0, 1, 0, 1, };
    c_int P_p[3] = {0, 2, 4, };

    c_int A_i[4] = {0, 1, 0, 2, };
    c_int A_p[3] = {0, 2, 4, };
```

These are used later to create matrices

```[c]
    data->P = csc_matrix(data->n, data->n, P_nnz, P_x, P_i, P_p);
    data->A = csc_matrix(data->m, data->n, A_nnz, A_x, A_i, A_p);
```

From the code, it looks like ``csc_matrix`` generates a ``csc`` struct. In the comments declaring that struct (in ``types.h``), I see some comments that describe ``P_i`` and ``P_p`` as the row and column indices. However, I am not understanding how this works. In particular, why is there a 4 in the last entry of ``P_p``?

Thanks.

**Comment by bstellato** [comment]
This is the **Compressed Sparse Column (CSC)** format. It is very common when describing sparse matrix. `P->i` are the row indices and `P->p` are the column pointers (not the column indices!). The column pointers are pointer to the first elements of `P->x` in every column (if there are no elements in that column, they point to next element in the `P->x` array). The last element of `P->p` corresponds to the total number of nonzeros in the matrix by construction. That's why it is `4` in the demo case. 

You are confusing the CSC format with the triplet format (also called coordinate format COO) where you have `P->i` as row index and `P->j` as the column index. With the CSC format the `P->p` vector is usually much shorter than `P->j` (`num_col + 1` instead of `num_nonzeros`). That's why it is called "compressed".

I suggest you to have a look at [this page](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csc_matrix.html) for an example on how CSC works. You can find other example [here](https://docs.oracle.com/cd/E19061-01/hpc.cluster5/817-0086-10/prog-sparse-support.html).

**Comment by esquires** [comment]
Thanks for the clarification.

**Comment by rtk-artista** [comment]
Can you kindly explain the pointers to the column A->p concept again? I am not able to apply the concept to a 36*36 matrix in my project.

**Comment by goulart-paul** [comment]
There is an example here. http://www.numerical.rl.ac.uk/spral/doc/latest/C/csc_format.html

In the example, `ptr` corresponds to our `A->p`, `row` corresponds to our `A->i` and `val` corresponds to `A->x`.

**Comment by rtk-artista** [comment]
So, if a column contains all zeros, will the corresponding element of the
A_p be zero?
eg:  [1 0 1; 0 0 4] -> will A_p be [0, 1, 0, 3] ?

**Comment by goulart-paul** [comment]
It would be [0,1,1,3]

**Comment by rtk-artista** [comment]
thanks
