### ISSUE TITLE
csc_matrix c_int - unsigned

### ISSUE THREAD

**Issue by ng5** [oxfordcontrol/osqp#87]
Thanks a lot for building this library. I'm looking forward to use this library to replace QP solver provided by CGAL library which is not that performant when matrix size increase. 

Couple of things, i noticed:

1. csc_matrix - c_int - Can this be please changed to use size_t or unsigned integers for colptr and rowids.  (Happy to send PR if this is deemed acceptable).

2. I'm using this to solve minimum portfolio variance as shown in the examples - however covariance matrix (P) is relatively dense. I agree that constraint matrix (A) is sparse. Is this library suitable for dense P matrix?

Thank you for reading and appreciate any inputs.

Regards,
Rohit

**Comment by goulart-paul** [comment]
Thanks a lot for building this library. I'm looking forward to use this library to replace QP solver provided by CGAL library which is not that performant when matrix size increase.

Thanks for your interest in our solver.

Couple of things, i noticed:

csc_matrix - c_int - Can this be please changed to use size_t or unsigned integers for colptr and rowids. (Happy to send PR if this is deemed acceptable).

We have not done this because we only want to work with a single integer and a single floating point type internally.   There are at least a few places where operations on CSC indexing data uses negative values, e.g. in the calculation of an elimination tree in the LDL factorisation.  Changing to unsigned types for indexing could cause problems for an application in which the memory used for elimination tree calculation is then also used to store the CSC indices.  Such a change would also need to be propagated to all of our interfaces.

A quick survey of other codes that use CSC data just now seems to show that the row/col indices are defined both ways, i.e. there is no clear agreement between various codes about signed or unsigned formats.   I think you will need to handle this conversion yourself before calling the solver.

I'm using this to solve minimum portfolio variance as shown in the examples - however covariance matrix (P) is relatively dense. I agree that constraint matrix (A) is sparse. Is this library suitable for dense P matrix?

It is not - you will need to convert everything to CSC.


Thank you for reading and appreciate any inputs.

Regards,
Rohit

**Comment by ng5** [comment]
Thanks Paul for the explanation. I will go ahead and compare the results with CGAL QPSolver.

**Comment by ng5** [comment]
I have run a benchmark and OSQP is close to 100 times faster than QP Solver provided by CGAL for portfolio optimization consisting of 50 assets.
