### ISSUE TITLE
Conversion to CSC matrices is slow

### ISSUE THREAD

**Issue by stephane-caron** [oxfordcontrol/osqp#9]
Currently the Python API requires `P` and `A` to be in CSC format.

Problem is: on small instances, it can take much more time to convert to CSC than to solve the QP itself. In this  [small example](https://github.com/stephane-caron/qpsolvers/blob/master/examples/small.py) where `P` and `A` are 3x3, CSC conversions takes ~200 µs on my machine, versus ~20 µs taken to solve the QP itself.
```
In [17]: P.shape
Out[17]: (3, 3)

In [18]: %timeit csc_matrix(P)
10000 loops, best of 3: 116 µs per loop
```
Could the API allow for dense `numpy.array` arguments for `P` and `A`?

**Comment by bstellato** [comment]
Thank you for adding OSQP to your [unified QP API](https://github.com/stephane-caron/qpsolvers)! OSQP internally supports sparse matrices. Thus, the dense-to-sparse conversion has to happen somewhere.

Not that most solvers, including commercial ones, support sparse matrices internally. In most practical applications, problems have a very specific sparse structure.

In my opinion, I would use the time returned by the individual solvers to make the comparison fair. The Python timer includes some overhead that could change the outcome. 

OSQP returns the internally computed run time in the `results` structure as `results.info.run_time`.  GUROBI, for example, returns the computation time in `model.Runtime`.

I suggest you to use those values instead of the `timeit` reported time.

**Comment by stephane-caron** [comment]
> The fact that it is slow is related to Scipy.

Yes, that's why I was wondering if there would be a way to circumvent Scipy, for instance if you subsequently convert from Scipy to your own internal representation?

> I suggest you to use those values instead of the timeit reported time.

Well, at the end of the day, the price paid is `total_time = build_time + run_time`. (Feel free to let me know if there is a better way than `%timeit` to measure this total computation time.)

For example, the MPC I'm working on runs with a loop cycle of 5 ms (where `P` and `A` are state-dependent so the QP is rebuilt at each cycle). I think Scipy's sparse matrices are too slow for such settings (e.g., it takes ~50 µs to update *one entry* of these matrices).

**Comment by bstellato** [comment]
The OSQP representation is Compressed Sparse Column (CSC) format which corresponds exactly to the Scipy representation. No conversion from `scipy.sparse.csc_matrix` is performed.

Python is mainly used as a prototyping language. It is useful to check how much time it takes if the solver is called from a lower level language (C/C++).

If you are dealing with MPC at 5ms loop cycles, I suggest you to check the timings as I said before, and then to implement the loop in a faster language (C/C++ or also Julia/Matlab).  

Note that there are two possible MPC formulations: *dense* (suitable for qpOASES) where the only variables are the inputs and *sparse* (suitable for sparse solvers like OSQP) where the variables are both inputs and states.

If you have a question related to your MPC formulation as QP, I am happy to discuss it in the [OSQP mailing list](https://groups.google.com/forum/#!forum/osqp).

**Comment by stephane-caron** [comment]
OK. Thanks for your feedback :)
