### ISSUE TITLE
Consider use C++ object oriented design in future version.

### ISSUE THREAD

**Issue by lianglia-apollo** [oxfordcontrol/osqp#94]

**Comment by gbanjac** [comment]
Do you have any difficulties in using OSQP from C++?

There are several reasons we decided to design OSQP using the C language, one of which is to support [code generation for embedded systems](https://osqp.org/docs/codegen/index.html). A complete redesign of the whole project is most likely not going to happen since that would also require updating all the [interfaces](https://osqp.org/docs/interfaces/index.html). Also, I do not see a clear benefit in having C++ version of OSQP.

**Comment by bstellato** [comment]
You can call OSQP from C++ already. If you need Eigen, you could directly use [the OSQP eigen interface](https://github.com/robotology/osqp-eigen). 

I have [already asked you](https://github.com/oxfordcontrol/osqp/pull/78#discussion_r219549414) why the current configuration does not work for you and I did not get any reply. It would be helpful if you could provide more details about your issue.

**Comment by lianglia-apollo** [comment]
Thanks for sharing the eigen interface. The current interface works.
